export const routesPath = {
	HOME: '/',
	WELCOME: '/welcome',
	RULES: '/rules',
	LOGIN: '/login',
	SELECT_ACTION: '/select-action',
	CREATE_PASSWORD: '/create-password',
	SEED_PHRASE_RULES: '/seed-phrase-rules',
	IMPORT_SEED_PHRASE: '/import-with-seed-phrase',
	SEED_PHRASE: '/seed-phrase',
	CONFIRM_SEED_PHRASE: '/confirm-seed-phrase',
	SETTINGS: '/settings',
	SETTINGS_SUPPORT: '/settings/support',
	SETTINGS_ADVANCED: '/settings/advanced',
	SETTINGS_CONTACTS: '/settings/contacts',
	SETTINGS_SECURITY_PRIVACY: '/settings/security-privacy',
	SETTINGS_WARNINGS: '/settings/warnings',
	SETTINGS_NETWORKS: '/settings/networks',
	SETTINGS_GENERAL_INFORMATION: '/settings/general-information',
	SETTINGS_PERMISSIONS: '/settings/permissions',
	BALANCE_DETAIL: '/balance-detail/:name',
	VALIDATORS: '/validators',
	SEND: '/send',
	ACTIVE_MESSAGE: '/active-message',
}
